# Generated by Django 4.2 on 2023-07-14 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Domain_Pfam",
            fields=[
                (
                    "domain_id",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
                ("domain_desc", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Organisms",
            fields=[
                ("taxa_id", models.IntegerField(primary_key=True, serialize=False)),
                ("clade", models.CharField(max_length=1)),
                ("genus", models.CharField(max_length=200)),
                ("species", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Proteins",
            fields=[
                (
                    "protein_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("sequence", models.CharField(max_length=200)),
                ("length", models.IntegerField()),
                (
                    "taxonomy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organisms",
                        to="biosciapp.organisms",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Domains",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("desc", models.CharField(max_length=200)),
                ("start", models.IntegerField()),
                ("end", models.IntegerField()),
                (
                    "pfam",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domain_pfam",
                        to="biosciapp.domain_pfam",
                    ),
                ),
                (
                    "protein",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="biosciapp.proteins",
                    ),
                ),
            ],
        ),
    ]
