# Generated by Django 4.2 on 2023-07-14 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("biosciapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="domains",
            old_name="pfam",
            new_name="domain",
        ),
    ]
